create table Roles (
  RoleID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  RoleName VARCHAR(10) NOT NULL,
  Description VARCHAR(50)
);

CREATE TABLE Users (
  UserID uuid PRIMARY KEY,
  Password text,
  FirstName VARCHAR (20),
  LastName VARCHAR(20),
  RoleID INT,
  Created_at timestamp,
  constraint RoleFK foreign key (RoleID) references Roles(RoleID)
);